sudo: required
language: java
install: true

services:
  - docker

addons:
  sonarcloud:
    organization: "mrinal-bhattacharya-github"
    token:
      secure: $SONAR_TOKEN

jdk:
 - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login –u=mrinalbhattacharya –p=Docker@1987 docker.io
- docker build -f Dockerfile -t mrinalbhattacharya/restful-api-springboot-docker:latest .
- echo "build and tag is done"
- docker images
- docker container ls
- docker push mrinalbhattacharya/restful-api-springboot-docker:latest
#  - sh ./deploy_heroku.sh
#deploy:
#  provider: heroku
#  api-key:
#    secure: $HEROKU_API_KEY
#  app: gamestore-api-mrinal
################a19cf6da3e09d2096f790b3d3f1172deeea7e9d7##########################nnnnnjjjjjsssssyyy
