# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - iaeaim(stage)
env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  JAVA_VERSION: '8'                  # set this to the Java version to use
  DISTRIBUTION: zulu
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java version
      uses: actions/setup-java@v3.0.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install
      
    - name: 'Download artifact from build job'
      uses: actions/download-artifact@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry, Build and Push
      uses: azure/docker-login@v1
      with:
        login-server: https://mrinalall.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3cbbcd5b428c4b2e97d8a07799566c7f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_17fa3006914b4ca4882a1bc8af190c37 }}
    - run: |
          ls
          docker build . -t ${{ secrets.AzureAppService_ContainerUsername_3cbbcd5b428c4b2e97d8a07799566c7f }}/aimapp:${{ github.sha }}
          docker push ${{ secrets.AzureAppService_ContainerUsername_3cbbcd5b428c4b2e97d8a07799566c7f }}/aimapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'iaeaim'
        slot-name: 'stage'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_05e10d2d8a704992af25800d3b036b74 }}
        images: 'mrinalall.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3cbbcd5b428c4b2e97d8a07799566c7f }}/mrinalall:${{ github.sha }}'
