# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aimdocker(stage)
env:
  JAVA_VERSION: '8'                  # set this to the Java version to use
  DISTRIBUTION: zulu 
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java version
      uses: actions/setup-java@v3.0.0
      with:
       java-version: ${{ env.JAVA_VERSION }}
       distribution: ${{ env.DISTRIBUTION }}
       cache: 'maven'
    - name: Build with Maven
      run: mvn clean install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://iaeall.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7281541995474d66819b2ca2132f9ef5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_51ed0aacb36249c9ace0f539d684c0b7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: iaeall.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7281541995474d66819b2ca2132f9ef5 }}/aimapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aimdocker'
        slot-name: 'stage'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_34f4d5db5a1f45d88abfd6611322d830 }}
        images: 'iaeall.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7281541995474d66819b2ca2132f9ef5 }}/aimapp:${{ github.sha }}'
